// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteNoise.Infra.Data.Contexts;

namespace WhiteNoise.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516181817_NewTablesCreation")]
    partial class NewTablesCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(90)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Alergia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(90)");

                    b.Property<Guid?>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Alergia");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.EstadoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadoClinico");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Internacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(90)");

                    b.Property<int?>("TipoSaida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Internacao");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataInternacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("EstadoClinicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InternacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("EstadoClinicoId");

                    b.HasIndex("InternacaoId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.ToTable("Prontuario");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Alergia", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Prontuario", null)
                        .WithMany("Alergias")
                        .HasForeignKey("ProntuarioId");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId");

                    b.HasOne("WhiteNoise.Domain.Entities.EstadoClinico", "EstadoClinico")
                        .WithMany()
                        .HasForeignKey("EstadoClinicoId");

                    b.HasOne("WhiteNoise.Domain.Entities.Internacao", "Internacao")
                        .WithMany()
                        .HasForeignKey("InternacaoId");

                    b.HasOne("WhiteNoise.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
