// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteNoise.Infra.Data.Contexts;

namespace WhiteNoise.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(500);

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.EstadoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadoClinico");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Internacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LeitoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoSaida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeitoId")
                        .IsUnique()
                        .HasFilter("[LeitoId] IS NOT NULL");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioId")
                        .IsUnique()
                        .HasFilter("[ProntuarioId] IS NOT NULL");

                    b.ToTable("Internacao");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Leito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(90)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Leito");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("EstadoClinicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(100);

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoClinicoId");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(100);

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Profissional");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(500);

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("varchar(90)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Prontuario");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId");

                    b.HasOne("WhiteNoise.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ProfissionalId");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Internacao", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Leito", "Leito")
                        .WithOne()
                        .HasForeignKey("WhiteNoise.Domain.Entities.Internacao", "LeitoId");

                    b.HasOne("WhiteNoise.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Internacoes")
                        .HasForeignKey("PacienteId");

                    b.HasOne("WhiteNoise.Domain.Entities.Prontuario", "Prontuario")
                        .WithOne()
                        .HasForeignKey("WhiteNoise.Domain.Entities.Internacao", "ProntuarioId");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Leito", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Leitos")
                        .HasForeignKey("DepartamentoId");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.EstadoClinico", "EstadoClinico")
                        .WithMany()
                        .HasForeignKey("EstadoClinicoId");
                });

            modelBuilder.Entity("WhiteNoise.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("WhiteNoise.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Profissionais")
                        .HasForeignKey("DepartamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
